 <?php foreach ($images as $img) { ?>
        <div class="image">
            <div>
                <img src="images/img_<?= $img["Id"]?>.<?= $img["extension"]?>" style="width: 100px" alt="">
                <a role="button" class="btn btn-primary btn-sm deleteImg" data-img-id="<?=$img["Id"]?>">x</a>
            </div>

            <div id="image-tags-<?= $img["Id"]?>">
                <?php foreach (Tags::getImageTagsByImageId($img["Id"]) as $tag) { ?>
                    <span class="tag-body badge badge-info">
                        <?= $tag["tag"]?> <span class="deleteTag" data-tag-id="<?=$tag["Id"]?>">x</span>
                    </span>
                <?php } ?>
            </div>

            <div class="addTagForm">
                Add tag:
                <input type="text" class="addTagText">
                <input type="button"
                       class="addTagButton"
                       data-image-id="<?= $img["Id"]?>"
                       value="Add">
            </div>
            <hr>
        </div>
    <?php } ?>