<div id="images-list">
<?php foreach ($images as $img) { ?>
        <div class="image">
            <div>
                <img src="images/img_<?= $img["Id"]?>.<?= $img["extension"]?>">
                <button role="button" class="btn btn-outline-light btn-sm deleteImg" data-img-id="<?=$img["Id"]?>">x</button>
            </div>

            <div class="input-group mb-3 addTagForm">
                <input type="text" class="form-control addTagText"
                       placeholder="New Tag Name"
                       aria-label="New Tag Name"
                       aria-describedby="basic-addon2">
                <div class="input-group-append">
                    <button data-image-id="<?= $img["Id"]?>"
                            class="btn btn-outline-secondary addTagButton" type="button">
                        Add Tag
                    </button>
                </div>
            </div>

            <div id="image-tags-<?= $img["Id"]?>">
                <?php foreach (Tags::getImageTagsByImageId($img["Id"]) as $tag) { ?>
                    <span class="tag-body badge badge-info">
                        <?= $tag["tag"]?> <span class="deleteTag" data-tag-id="<?=$tag["Id"]?>">x</span>
                    </span>
                <?php } ?>
            </div>
        </div>
    <?php } ?>
</div>

<hr>
<?php $pages = ceil($count / 6);?>
<script>
    window.currentImagesPage = <?= $current ?>;
    window.currentTag = '<?= $currentTag ?>';
</script>

<nav aria-label="Page navigation example">
    <ul class="pagination">
        <?php if ($current > 0) { ?>
            <li class="page-item"><a class="page-link" data-page="<?= $current - 1 ?>">Previous</a></li>
        <?php } ?>

        <?php for ($x = 0; $x < $pages; $x++) { ?>
            <li class="page-item <?= ($x == $current) ? "active" : "" ?>">
                <a class="page-link" data-page="<?= $x ?>"><?= $x + 1 ?>
                </a>
            </li>
        <?php } ?>

        <?php if ($current + 1 < $pages) { ?>
            <li class="page-item"><a class="page-link" data-page="<?= $current + 1 ?>">Next</a></li>
        <?php } ?>
    </ul>
    <span>Total: <?=$count?></span>
</nav>
