<h3>Total: <?=$count?></h3>
<?php foreach ($images as $img) { ?>
        <div class="image">
            <div>
                <img src="images/img_<?= $img["Id"]?>.<?= $img["extension"]?>" style="width: 100px" alt="">
                <a role="button" class="btn btn-primary btn-sm deleteImg" data-img-id="<?=$img["Id"]?>">x</a>
            </div>

            <div id="image-tags-<?= $img["Id"]?>">
                <?php foreach (Tags::getImageTagsByImageId($img["Id"]) as $tag) { ?>
                    <span class="tag-body badge badge-info">
                        <?= $tag["tag"]?> <span class="deleteTag" data-tag-id="<?=$tag["Id"]?>">x</span>
                    </span>
                <?php } ?>
            </div>

            <div class="addTagForm">
                Add tag:
                <input type="text" class="addTagText">
                <input type="button"
                       class="addTagButton"
                       data-image-id="<?= $img["Id"]?>"
                       value="Add">
            </div>
            <hr>
        </div>
    <?php } ?>

<?php $pages = ceil($count / 5);?>
<script>
    window.currentImagesPage = <?= $current ?>;
    window.currentTag = '<?= $currentTag ?>';
</script>

<nav aria-label="Page navigation example">
    <ul class="pagination">
        <?php if ($current > 0) { ?>
            <li class="page-item"><a class="page-link" data-page="<?= $current - 1 ?>">Previous</a></li>
        <?php } ?>

        <?php for ($x = 0; $x < $pages; $x++) { ?>
            <li class="page-item <?= ($x == $current) ? "active" : "" ?>">
                <a class="page-link" data-page="<?= $x ?>"><?= $x + 1 ?>
                </a>
            </li>
        <?php } ?>

        <?php if ($current + 1 < $pages) { ?>
            <li class="page-item"><a class="page-link" data-page="<?= $current + 1 ?>">Next</a></li>
        <?php } ?>
    </ul>
</nav>
